GET /rooms
> Accept: application/json
> User-Agent: KATT
< 200
< Content-Type: application/json
[
  {
    "occupied": [],
    "name": "C01"
  },
  {
    "occupied": [
      {
        "start_time": "2021-04-10T17:24:31Z",
        "end_time":   "2021-04-10T18:24:31Z"
      }
    ],
    "name": "C02"
  },
  {
    "occupied": [],
    "name": "C03"
  },
  {
    "occupied": [],
    "name": "C04"
  },
  {
    "occupied": [],
    "name": "C05"
  },
  {
    "occupied": [],
    "name": "C06"
  },
  {
    "occupied": [],
    "name": "C07"
  },
  {
    "occupied": [],
    "name": "C08"
  },
  {
    "occupied": [],
    "name": "C09"
  },
  {
    "occupied": [],
    "name": "C10"
  }
]