GET /rooms
> Accept: application/json
> User-Agent: KATT
< 200
< Content-Type: application/json
[
  {
    "occupied": [],
    "name": "P01"
  },
  {
    "occupied": [],
    "name": "P02"
  },
  {
    "occupied": [],
    "name": "P03"
  },
  {
    "occupied": [],
    "name": "P04"
  },
  {
    "occupied": [],
    "name": "P05"
  },
  {
    "occupied": [],
    "name": "P06"
  },
  {
    "occupied": [],
    "name": "P07"
  },
  {
    "occupied": [],
    "name": "P08"
  },
  {
    "occupied": [],
    "name": "P09"
  },
  {
    "occupied": [],
    "name": "P10"
  }
]